import {
  AlertCircle, AlignJustify, Calendar,
  Check, ChevronDown, ChevronLeft, ChevronRight,
  Clock, Edit, FileCheck, FileDown, FileText,
  HelpCircle, LayoutDashboard, ListChecks, Loader2,
  Menu, Mic, MicOff,
  MoreVertical, Pause, Play, Plus, Save, Search,
  Settings, Share, Stethoscope, StopCircle, Trash, User,
  UserPlus, Users, X
} from "lucide-react";

export const Icons = {
  logo: Stethoscope,
  stethoscope: Stethoscope,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  menu: Menu,
  spinner: Loader2,
  settings: Settings,
  mic: Mic,
  micOff: MicOff,
  play: Play,
  pause: Pause,
  stopCircle: StopCircle,
  fileText: FileText,
  fileCheck: FileCheck,
  fileDown: FileDown,
  clock: Clock,
  edit: Edit,
  trash: Trash,
  save: Save,
  share: Share,
  search: Search,
  check: Check,
  users: Users,
  user: User,
  userPlus: UserPlus,
  alertCircle: AlertCircle,
  helpCircle: HelpCircle,
  calendar: Calendar,
  layoutDashboard: LayoutDashboard,
  plus: Plus,
  listChecks: ListChecks,
  more: MoreVertical,
  align: AlignJustify,
  x: X,
};